### DISCUSSION TITLE
Add a "file / source" value for code snippets to show where the code comes from

### DISCUSSION THREAD

**Discussion by JPustkuchen** [slidevjs/slidev#1112] [Ideas]
Often when using code-snippets you'd like to show the file source of the code below the code. Doing that as regular text doesn't look good, so it would be great, to have that functionality included somewhere in the code highlighting.

Something like:
~~~
```yml
regions:
  header: Header
  primary_menu: Primary menu
  secondary_menu: Secondary menu
  [...]
```(xyz/my-example.yml)
~~~

or

~~~
```yml(xyz/my-example.yml)
regions:
  header: Header
  primary_menu: Primary menu
  secondary_menu: Secondary menu
  [...]
```
~~~
what ever is allowed and possible.

I'd expect the source file path / name to appear on the bottom right of the source highlighting perhaps?
