### DISCUSSION TITLE
Is there a way to change the line-height of code blocks using local styles?

### DISCUSSION THREAD

**Discussion by mikanIchinose** [slidevjs/slidev#1501] [Q&A] [answered]
I set the global style for code block like bellow.
Because almost all code block is short.

```css
:root {
    --slidev-code-font-size: 20px;
    --slidev-code-line-height: 28px;
}
```

But sometimes I write long code block.
So I'd like to change `font-size` and `line-height` locally.
As a result, `font-size` is changed, but `line-height` is not.

````md
```
// very loooong code...
```
<style>
/* #1 -> x */
code {
  font-size: 12px;
  line-height: 18px;
}
/* #2 -> x */
.slidev-code {
  line-height: 18px;
}
/* #3 -> x */
:root {
  --slidev-code-line-height: 18px;
}
</style>
````

Anyone know the way to change the line-height of code blocks using local styles?
