### DISCUSSION TITLE
How am I supposed to override the dark and light background colors?

### DISCUSSION THREAD

**Discussion by heyalexnet** [slidevjs/slidev#1976] [Q&A]
I want to override the background color (currently using the default theme). Right now, I'm adding this snippet in an `index.css` file:

```css
.dark .slidev-slide-content {
  background-color: #010747 !important;
}
```

But I'm sure there's a better way. How can I achieve that?

Also, doing it this way does not work with the PDF export: `npx slidev export --dark`. The slides are exported with the original dark color, not mine.
