### DISCUSSION TITLE
How to make text Copyable?

### DISCUSSION THREAD

**Discussion by ahandsel** [slidevjs/slidev#388] [Q&A]
I really like Slidev but unlike [reveal.js](https://revealjs.com/), I cannot copy the text from my Slidev slides.
*Being dyslexic, I need my slides to be readable by my text-to-audio programs.*

I noticed that Slidev's CSS includes the following:
```css
{
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none
}
```

How can I disable this CSS that prevents simple copying of text?

Thank you for your time!
