### ISSUE TITLE
Feature request: Hide scrollbar in iframe-* layout.

### ISSUE THREAD

**Issue by VergeDX** [slidevjs/slidev#1022]
**Is your feature request related to a problem? Please describe.**

Hidden scrollbar from iframe (in iframe-* layout),  
or Markdown code section (seems useless?)

**Describe the solution you'd like**

An option in iframe-* layout.

**Describe alternatives you've considered**

A hack for overflow the scrollbar element

```css
iframe {
    height: 102% !important;
}
```
