### ISSUE TITLE
gh actions fails: what did I miss? theme-default is not found

### ISSUE THREAD

**Issue by draptik** [slidevjs/slidev#1171]
I am still using slidev version 0.40.3.

Deploying via gh-actions fails with the following error message:

[deploy](https://github.com/draptik/2023-modern-linux-cli-tools/actions/runs/6713039137/job/18244084820#step:7:41)
```
The directory you're trying to deploy named /home/runner/work/2023-modern-linux-cli-tools/2023-modern-linux-cli-tools/presentation/dist doesn't exist. Please double check the path and any prerequisite build scripts and try again. ❗
```

I've been using the following ci-script without any issues until today:

https://github.com/draptik/2023-modern-linux-cli-tools/blob/wjax/.github/workflows/deploy-wjax.yml

```
name: Deploy pages
on:
  push:
    branches:
      - wjax

jobs:
  deploy:

    env:
      PRESENTATION_FOLDER: 'presentation'
      TARGET_REPO_NAME: '2023-11-wjax-modern-linux-cli-tools'
      TARGET_GITHUB_OWNER: 'draptik'

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
            cd ${{ env.PRESENTATION_FOLDER }}
            npm install

      - name: Install slidev
        run:  |
            cd ${{ env.PRESENTATION_FOLDER }}
            npm i -g @slidev/cli

      # Ensure to set the base directory to the current branch name
      - name: Build
        run: |
            cd ${{ env.PRESENTATION_FOLDER }}
            slidev build --base '/${{ env.TARGET_REPO_NAME }}/'

      - name: Deploy to target repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          single-commit: true
          folder: ${{ env.PRESENTATION_FOLDER }}/dist # The folder the action should deploy
          repository-name: '${{ env.TARGET_GITHUB_OWNER }}/${{ env.TARGET_REPO_NAME }}'
          token: ${{ secrets.SLIDEV_TOKEN }}
```

What has changed?

What is the best approach for fixing this?

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Browser: Chromium
 - Slidev version: 0.40.3

Thanks
Patrick
