### ISSUE TITLE
How to change spacing between different footnotes?

### ISSUE THREAD

**Issue by liuguanfu1120** [slidevjs/slidev#1242]
**Describe the bug**
It seems that I cannot change the spacing between different footnots. I have tried that
```css
<style>
.footnotes-sep {
  @apply mt-10 opacity-10;
}
.footnotes {
  @apply text-sm opacity-75;
  line-height: 12;
  font-size: 10px;
  padding-bottom: 5px;
}
.footnote-backref {
  display: none;
}
</style>
```
If the line-height is changed, the spacing will not change, like changing it from 12 to 1200. 
The footnotes are like the following pictures:

<img width="415" alt="image" src="https://github.com/slidevjs/slidev/assets/94448438/6615b560-b17a-4612-904d-a758fbce00c1">

The spacing between two footnote items seems to be too large, it will be very good if there is some way to reduce the spacing, especially when the number of footnote items is large.

**To Reproduce**
1. Just use the default template from slidev's official website
2. Add serveral footnotes in any pages of the template
3. Try to reduce the spacing of footnotes

**Desktop (please complete the following information):**
 - OS: Ventura 13.5.2
 - Browser: Firefox 121.0 (64-bit)
 - Slidev version: 0.43.15
