### ISSUE TITLE
Static hosting for multiple slides broken since major upgrade to 0.48.X

### ISSUE THREAD

**Issue by very-doge-wow** [slidevjs/slidev#1522]
**Describe the bug**

We're rendering multiple slides and then tried hosting them statically both using an nginx webserver as well as GitLab Pages.

This is our project directory structure:

* CONTRIBUTING.md
* LICENSE.md
* README.md
* index.html
* slidev
  * gitlab-da.md
  * img
  * itsm.md
  * node_modules
  * package-lock.json
  * package.json

The index.html is a simple index file which points to the sub-paths where the individual slides should be served. For example, the gitlab-da.md slide should be served under the URL `/gitlab-da`.

**On GitLab Pages**

We then execute this script in a GitLab CI pipeline in order to render the slides (example for GitLab Pages):

```yaml
build_website:
  image: XXX/playwright:v1.43.0-jammy@sha256:c98d3e8860b3297bbb56550858e29c546b9ae623ba2b0e9e91a06bb945124f2f
  script:
    # install deps
    - |
      cd slidev
      npm ci
      npm i -D playwright-chromium
    # set correct base url for review/prod
    - |
      if [ -n "${CI_MERGE_REQUEST_ID}" ]; then
        export BASE="/-/docs/presentations/${SLIDE_NAME}/"
      else
        export BASE="/-/docs/presentations/-/jobs/${CI_JOB_ID}/artifacts/public/${SLIDE_NAME}/"
      fi
      echo "ℹ️ Base is ${BASE}"
    # render each presentation separately
    - |
      export OUT_DIR="${CI_PROJECT_DIR}/public"
      mkdir ${OUT_DIR}
      echo "const data = [" >> ${OUT_DIR}/slides.js
      for SLIDE in $(echo *.md); do
        echo "ℹ️ Rendering slide ${SLIDE}"
        SLIDE_NAME=${SLIDE/.md/}
        mkdir -p ${OUT_DIR}/${SLIDE_NAME}/img
        npx slidev build --out ${OUT_DIR}/${SLIDE_NAME} --base "${BASE}" ${SLIDE}
        npx slidev export ${SLIDE} --format png --range 1 --timeout 600000
        mv ${SLIDE_NAME}-export/001.png ${OUT_DIR}/${SLIDE_NAME}/img/preview_${SLIDE_NAME}.png
        echo \"${SLIDE}\", >> ${OUT_DIR}/slides.js
        echo "✅ Done rendering slide ${SLIDE}"
      done
      echo "];" >> ${OUT_DIR}/slides.js
    # move index page to outdir
    - mv ${CI_PROJECT_DIR}/index.html ${OUT_DIR}
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/public
```

We change the BASE for rendering as in GitLab Pages to create a review app we need to link to the job's artifacts instead of the GitLab Pages prod deployment URL. These files however of course will still get hosted on GitLab Pages.

When accessing the deployment under these URLs, we receive a 404 status code:
* `/-/docs/presentations/-/jobs/${CI_JOB_ID}/artifacts/public/gitlab-da`
* `/-/docs/presentations/-/jobs/${CI_JOB_ID}/artifacts/public/gitlab-da/`
* `/-/docs/presentations/-/jobs/${CI_JOB_ID}/artifacts/public/gitlab-da/1`

The only URL which is accessible, is `/-/docs/presentations/-/jobs/${CI_JOB_ID}/artifacts/public/gitlab-da/index.html`, which however returns a broken page that yields different errors in the console:

```
Failed to load resource: the server responded with a status of 404 ()
vue-SsZo2je5.js:1 
        
Failed to load resource: the server responded with a status of 404 ()
shiki-CE5jJmub.js:1 
       
Failed to load resource: the server responded with a status of 404 ()
index.html:1 Refused to apply style from 'XXX/-/docs/presentations//assets/modules/shiki-BSchMNmt.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
index.html:1 Refused to apply style from 'XXX/-/docs/presentations//assets/index-Ds8jeKp0.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
index-B5rj8lQp.js:1 
        
Failed to load resource: the server responded with a status of 404 ()
index.html:1 Refused to apply style from 'XXX/-/docs/presentations//assets/modules/shiki-BSchMNmt.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
index.html:1 Refused to apply style from 'XXX/-/docs/presentations//assets/index-Ds8jeKp0.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**On nginx**

We also tried hosting using our own nginx webserver, which is configured as follows:

```conf
worker_processes  1;

error_log  /tmp/error.log warn;
pid        /tmp/nginx.pid;

events {
    worker_connections  1024;
}

http {
    charset utf-8;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /tmp/access.log  main;

    sendfile        on;

    keepalive_timeout  65;


    # Temporary directories for kubernetes "readonlyfilesystem"
    client_body_temp_path /tmp/nginx-client-body;
    proxy_temp_path       /tmp/nginx-proxy;
    fastcgi_temp_path     /tmp/nginx-fastcgi;
    uwsgi_temp_path       /tmp/nginx-uwsgi;
    scgi_temp_path        /tmp/nginx-scgi;

    # Override server directive of default.conf and 
    # add rewrite rule to prevent routing errors of slidev slides
    server {
        listen       8080;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

    rewrite_log on;
    rewrite ^/(.+)/[0-9]+ /$1/ last;
    }

include /etc/nginx/conf.d/*.conf;
}
```

We render the slides like this in the GitLab CI pipeline:

```yaml
build_website:
  image: XXX/playwright:v1.43.0-jammy@sha256:c98d3e8860b3297bbb56550858e29c546b9ae623ba2b0e9e91a06bb945124f2f
  stage: build_artifact
  tags:
    - non-prod-workload
  script:
    - cd slidev
    - npm ci
    - npm i -D playwright-chromium
    # render each presentation separately
    - |
      mkdir render
      echo "const data = [" >> ./render/slides.js
      for SLIDE in $(echo *.md); do
        echo "ℹ️ Rendering slide ${SLIDE}"
        SLIDE_NAME=${SLIDE/.md/}
        mkdir -p render/${SLIDE_NAME}
        npx slidev build --base /${SLIDE_NAME}/ ${SLIDE}
        mv dist/* render/${SLIDE_NAME}
        npx slidev export ${SLIDE} --format png --range 1 --timeout 600000
        mkdir render/${SLIDE_NAME}/img
        mv ${SLIDE_NAME}-export/001.png render/${SLIDE_NAME}/img/preview_${SLIDE_NAME}.png
        rm -rf dist
        echo \"${SLIDE_NAME}\", >> ./render/slides.js
        # fix missing img assets
        cp img/* render/${SLIDE_NAME}/img
        echo "✅ Done rendering slide ${SLIDE}"
      done
      echo "];" >> ./render/slides.js
    # move to outdir
    - mv ./render ../public
    - mv ../index.html ../public
  interruptible: true
  needs: []
  artifacts:
    paths:
      - public
```

The rendered slides then get added to a docker image based on nginx like this:

```dockerfile
FROM nginx

USER root

COPY nginx.conf /etc/nginx/nginx.conf
COPY public/ /usr/share/nginx/html

USER 1000
```

When deploying this image, we can access the index page normally.
Then, when trying to access one of the slides under a sub-path, we see this:
![image](https://github.com/slidevjs/slidev/assets/95224950/34a055f8-c307-44e7-a96a-dc597980af14)

The console returns 30 errors along the lines of these 2:

```
Failed to load resource: the server responded with a status of 403 (Forbidden)
2-DnRVisuv.css:1

Failed to load slide 1: TypeError: Failed to fetch dynamically imported module: https://XXX/gitlab-da/assets/1-D5ziA_Ds.js
```

This approach (i.e. hosting on nginx and rendering as explained above) used to work fine until version 0.47.5. Only after the major upgrade to 0.48.X does this break our deployment.

**To Reproduce**

1. Create a slidev project with multiple slides (slidev version >= 0.48)
2. Render them individually and move the output to `public/${SLIDE}` directory
3. Add the artifacts to an nginx webserver/host them on GitLab Pages

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Google Chrome
- Slidev version: 0.48.9
