### ISSUE TITLE
Per slide transition ignored

### ISSUE THREAD

**Issue by GioPan04** [slidevjs/slidev#1752]
**Describe the bug**

If I set a `transition` propriety in the frontmatter of a slide, the transition will be ignored and the default one (set in the initial page frontmatter) will play.

**Minimal reproduction**
`style.css`
```css
.my-transition-enter-active,
.my-transition-leave-active {
    transition: opacity 0.5s ease;
}

.my-transition-enter-from,
.my-transition-leave-to {
    opacity: 0;
}
```
`slides.md`
```md
---
theme: seriph
# transition: fade-out
mdc: true
---

# Test slide

---

# Another slide

---
transition: my-transition
---

# Last slide

```

**Steps to reproduce the behavior:**

Just copy and paste the `slides.md` and `style.css` files into a new project and run

**Environment**

- Slidev version: 0.49.16
- Browser: Firefox and Chromium
- OS: Linux
