### ISSUE TITLE
theme with custom assets

### ISSUE THREAD

**Issue by ameinhardt** [slidevjs/slidev#190]
**Describe the bug**
I would like to create a theme module (node_modules/slidev-theme-xyz) that uses custom font assets in its `@font-face` definition, In `main.css`, I tried:
```
@font-face {
  font-family: My Font;
  font-style: normal;
  font-weight: 400;
  src: url('/fonts/myFont.eot');
  src: url('/fonts/myFont.woff') format('woff'),url('/fonts/myFont.woff2') format('woff2'),url('/fonts/myFont.ttf') format('truetype')
}
```
That works fine, if the fonts are available in the `<project root>/public/fonts` folder, but not in the theme dependency.

**To Reproduce**
1. Add a custom font to the main.css of a reusable theme
2. Assign the font name to `windi.config.ts` / `theme.extend.fontFamily.sans`
2. Run dev server `npm run dev`

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Slidev version: 0.10.5

How can custom slidev themes have static (css) assets?

**Comment by antfu** [comment]
Try this?

```css
@font-face {
  font-family: My Font;
  font-style: normal;
  font-weight: 400;
  src: url('/myFont.eot');
  src: url('/myFont.woff') format('woff'),url('/myFont.woff2') format('woff2'),url('/myFont.ttf') format('truetype')
}
```
