### ISSUE TITLE
for image-left/image-right layouts add a setting to set image width

### ISSUE THREAD

**Issue by alex-176** [slidevjs/slidev#2064]
for layouts `image-left`/`image-right` it'd be great to have a simple way to change how much space the image takes on the slide. currently, it's 50% and I did not find a simple way to change it.

e.g. in frontmatter:
`imageWidth: 30% # to make an image take only 30% of the full slide width`

maybe there is a workaround with <style> (that I did not find) but the straightforward setting is clearer.

**Comment by snomos** [comment]
You can change it with `backgroundSize`, e.g. something like this:

```yaml
layout: image-right
image: ./images/your-image.png
backgroundSize: 30em 50%
```

Worked nicely for me.
