### ISSUE TITLE
`` is not removed in inline code block

### ISSUE THREAD

**Issue by yjl9903** [slidevjs/slidev#208]
**Describe the bug**
`` is not removed in inline code block

![image](https://user-images.githubusercontent.com/30072175/120275334-baa9ff80-c2e3-11eb-98ad-631bb7ab74c0.png)

**To Reproduce**
Just add `some code ...` in official template

**Desktop (please complete the following information):**
 - OS: Windows10 20H2
 - Browser: Edge 91.0.864.37
 - Slidev version: 0.16.1

**Comment by yjl9903** [comment]
Oh, I find it just a default style.

```css
:not(pre) > code:before,
:not(pre) > code:after {
    content: '`';
    opacity: 0.50;
}
```
