### ISSUE TITLE
Google Fonts

### ISSUE THREAD

**Issue by TutoDS** [slidevjs/slidev#232]
Hi.
How to load multiple fonts with multiples font-weights.

Example:
```
fonts:
  # Normal Font
  sans: 'Poppins'
  # Serif Font
  serif: 'Playfair Display'
  # Code Font
  mono: 'Fira Code'
  # Provider
  provider: 'google'
```

I have this fonts, but I want the Playfair Display and Poppins with font weight, bold, normal and light.

And other thing, I think in my titles the font is not Poppins.

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/18479474/121126416-0565d300-c820-11eb-97d2-0b5aabeeb57f.png">

The extension **What Font?** appear this:
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/18479474/121126454-19113980-c820-11eb-9202-398491fbd80e.png">

Can help me?
