### ISSUE TITLE
Custom styles not being applied

### ISSUE THREAD

**Issue by jahirfiquitiva** [slidevjs/slidev#338]
**Describe the bug**
Hello, I am currently trying to override the colors for code snippets using prism highlighter.
The documentation is limited and doesn't say much.

I already have applied the changes with what the `prism-theme-vars` repo say, and also based on some theme styles I found. But it isn't working as expected, as my custom styles are not being imported.

<img width="736" alt="Shot 2021-09-01 at 11-51-37@2x" src="https://user-images.githubusercontent.com/10360816/131712690-6e1e4356-6a91-44b2-af15-be4a60c0064f.png">

![Shot 2021-09-01 at 11-52-10@2x](https://user-images.githubusercontent.com/10360816/131712628-8a8bf639-c6bd-4eb6-afe7-ceb8f6e65aee.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave
 - Slidev version: 0.22.7

**Comment by jahirfiquitiva** [comment]
Solved by putting all the `--prism` variables again like so:

```css
.dark {
    --prism-foreground: var(--text-primary);
    --prism-background: var(--primary);
    ...
}
```
