### ISSUE TITLE
How to implement highlight the current v-click target only?

### ISSUE THREAD

**Issue by enolive** [slidevjs/slidev#379]
I'm relatively new to Slidev. My skills in Tailwind/Windi CSS are rudimentary at best :wink: 

I am trying to implement something like mentioned in [How to prevent death by PowerPoint (10:52)](https://youtu.be/Iwpi1Lm6dFo?t=652) where only one statement has the focus, everything else is faded out.

The best way I can currently come up with to do that is something like this:

```markdown
---
class: fade
---

# Animations

<v-clicks>

- Only one item will be focused at one time!
- You can use this to your advantage!
- The human brain can only concentrate on a few things (speak: only one) at the same time.
- Use this for psychological warfare 😉.
- See also [How to prevent death by powerpoint 10:52](https://youtu.be/Iwpi1Lm6dFo?t=652)

</v-clicks>
```

using following css:

```css
.fade {
  .slidev-vclick-target {
    transition: all 500ms ease;
  }
  
  .slidev-vclick-hidden {
    transform: none;
  }

  .slidev-vclick-prior {
    @apply !opacity-50;
  }
}
```

Screenshot:

![grafik](https://user-images.githubusercontent.com/20992515/138126549-eeab69f3-e5d0-4fff-aaad-59f73cecd136.png)

Any better way doing this?

**Comment by enolive** [comment]
Thanks for pointing that out! While this seems to be a very useful feature, it does no meet my expectation I am trying to achieve

- with `<v-clicks fade>` the items will be initially faded out (instead of hidden) to appear in full opacity when clicked
- what I'd like to see is that only the current item is in full opacity. All future items are hidden and the prior items are in a lower opacity

Perhaps this slide from an upcoming presentation might help with the understanding (In german, but the content is irrelevant :wink:) of the animation effect I'd like to see:

https://enolive.github.io/intro-to-slidev/9

**Comment by antfu** [comment]
Then I think your current solution fits better for your need and that's how it designed to be (leverage the power of Web for full customization).

**Comment by MountNoperest** [comment]
I know this is a closed thread. Thanks @enolive for the code, I have been looking for a similar animation.
I have changed the code such that the opacity goes to 50% only for list elements; text-size increase, then decrease. Images on the same slide are then untouched. 

```css
.fade {
  .slidev-vclick-target {
    transition: all 500ms ease;
    font-size: 2rem;
  }
  .slidev-vclick-hidden {
    transform: none;
  }

  li.slidev-vclick-prior {
    font-size: 1rem;
    @apply opacity-50;
  }
}
```
