### ISSUE TITLE
feat: option for displaying badges with the language name next to a code block

### ISSUE THREAD

**Issue by enolive** [slidevjs/slidev#385]
**Is your feature request related to a problem? Please describe.**

I'd like to display the name of the programming language for a code.
This would be especially useful when making presentations that compare different programming languages.

**Describe the solution you'd like**

A code block has already a language tag used for syntax highlighting.

When the feature is turned on, slidev would display little labels containing the language name, for instance in the top right corner.

See also https://github.com/ThomasWeinert/reveal-badges for a similar implementation for RevealJS

**Describe alternatives you've considered**

I can encapsulate the code in a div container that provides the language name and a CSS class:

```html
<div class="badge" data-language="Kotlin">
``kotlin
println("Hello, World!")
``
</div>
```

```css
.badge {
  position: relative;
}

.badge::before {
  content: attr(data-language);
  @apply absolute z-10 rounded-xl bg-dark-50 p-2 -top-1 right-0 border border-gray-500 text-light-500 font-bold;
}
```
