### ISSUE TITLE
Running Slidev on Docker

### ISSUE THREAD

**Issue by tutods** [slidevjs/slidev#514]
## Description
I'm trying to run the Slidev presentation using a Dockerfile and Docker Compose. But when I access the `localhost:<port-i-set>` not working. On `0.0.0.0:<por-i-set>` the screen is flashing. 

![image](https://user-images.githubusercontent.com/18479474/157532102-afa68890-4747-4303-b645-19ea2fd9a4f1.png)

## To Reproduce
1. Create a Slidev presentation and create the Dockerfile with:
```dockerfile
FROM node:17-alpine3.14

WORKDIR /usr/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn

COPY . ./

EXPOSE 3030

CMD ["yarn", "dev"]
```

2. After that create the `docker-compose.yml` file with:
```yaml
version: '3.8'

services:
  presentation:
    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - '.:/usr/app'
      - '/usr/app/node_modules'

    ports:
      - 3031:3030
```

3. Run `docker-compose up` and try access the presentation.

## Details
 - OS: macOS
 - Browser: Safari and Firefox
 - Slidev version: 0.28.9

**Comment by tangramor** [comment]
I just implemented a new docker image for slidev because the image mentioned in official document is not working:

# Slidev Docker image

Work with [Slidev](https://sli.dev/). Just run following command in your work folder:

```bash
docker run --name slidev --rm -it \
    --user node \
    -v ${PWD}:/slidev \
    -p 3030:3030 \
    tangramor/slidev:latest
```

If your work folder is empty, it will generate an template `slides.md` and other related files under your work folder, and launch the server on port `3030`. 

You can access your slides from http://localhost:3030/


## Build deployable image

Or you can create your own slidev project to a docker image with Dockerfile:

```Dockerfile
FROM tangramor/slidev:latest

ADD . /slidev

```

Create the docker image: `docker build -t myppt .`

And run the container: `docker run --name myslides --rm --user node -p 3030:3030 myppt`

You can visit your slids from http://localhost:3030/


## Build hostable SPA (Single Page Application)

Run command `docker exec -i slidev npx slidev build` on the runing container `slidev`. It will generate static HTML files under `dist` folder.

You can host `dist` in a static web site such as Github pages or Gitlab pages. You can also host it by your self:

```bash
docker run --name myslides --rm -p 80:80 -v ${PWD}/dist:/usr/share/nginx/html nginx:alpine
```

Or create a static image with following Dockerfile:

```Dockerfile
FROM nginx:alpine

COPY dist /usr/share/nginx/html

```

Create the docker image: `docker build -t mystaticppt .`

And run the container: `docker run --name myslides --rm -p 80:80 mystaticppt`

You can visit your slids from http://localhost/

**Comment by TutoDS** [comment]
Thanks, and how you do the production (builded presentation) in docker-compose and docker file?

**Comment by TutoDS** [comment]
I tried using this code:

# Dockerfile
```yml
FROM node:alpine AS development

WORKDIR /usr/app

ENV PATH /usr/app/node_modules/.bin:$PATH

COPY package.json ./
COPY yarn.lock ./

# use --ignore-scripts to avoid the husky hooks
RUN yarn install --ignore-scripts
RUN npx playwright install

COPY . .

RUN yarn build

EXPOSE 3030

CMD ["yarn", "slidev", "--remote"]

FROM nginx:alpine AS production

WORKDIR /usr/app

COPY --from=development /usr/app/dist .
```

# Docker Compose
```yml
version: '3.8'

services:
  prod_presentation:
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile

    volumes:
      - .:/usr/app:ro

    ports:
      - 8081:80

```
