### ISSUE TITLE
How to make text Copyable?

### ISSUE THREAD

**Issue by ahandsel** [slidevjs/slidev#516]
**Is your feature request related to a problem? Please describe.**

I really like Slidev but unlike [reveal.js](https://revealjs.com/), I cannot copy the text from my Slidev slides.
*Being dyslexic, I need my slides to be readable by my text-to-audio programs.*

I noticed that Slidev's CSS includes the following:

```css
{
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none
}
```

How can I disable this CSS that prevents simple copying of text?

**Describe the solution you'd like**
A simple way to disable the CSS (mentioned above) to enable copying of text

Thank you for your time 🙇‍♂️
