### ISSUE TITLE
fonts doesn't change after i change it in frontmatter?

### ISSUE THREAD

**Issue by 15921483570** [slidevjs/slidev#529]
**Describe the bug**
the fonts doesn't show as i've specified in the frontmatter, according to https://sli.dev/custom/fonts.html.

**To Reproduce**
1. install slidev globally
2. excute `slidev` in a new created folder
3. edit the default `slides.md` file
4. add following configs in frontmatter:
    ```
    fonts:
      # basically the text
      sans: 'Robot'
      # use with `font-serif` css class from windicss
      serif: 'Robot Slab'
      # for code blocks, inline code, etc.
      mono: 'Fira Code'
    ```
5. the fonts are still PT series as default

**Desktop (please complete the following information):**
 - OS: mac os 11.6
 - Browser: chrome 99
 - Slidev version: 0.29.2 (global)
