### ISSUE TITLE
Exported PDF does not display images from the public directory

### ISSUE THREAD

**Issue by aazon** [slidevjs/slidev#815]
**Describe the bug**
A `slidev export` command does not insert local images from the `public` directory in the generated PDF file.

**To Reproduce**
1. Create a file `test.md` with the following content:
```yaml
---
theme: default
class: 'text-center'
highlighter: shiki
lineNumbers: false
drawings:
  persist: false
css: unocss
---

# TEST

---
layout: center
---

<img src="/test.jpg" />
```
2. Add an arbitrary image file `public/test.jpg`.
3. Export slides to PDF:
```bash
$ slidev export test.md
```

**Expected Result**
A file `test-export.pdf` contains two pages:
1. A page with the title "TEST".
2. A page with an image `public/test.jpg`. 

**Actual Result**
A file [test-export.pdf](https://github.com/slidevjs/slidev/files/10384504/test-export.pdf) contains two pages:
1. A page with a title "TEST".
2. A blank page. 

**Desktop (please complete the following information):**
 - OS: macOS 13.1
 - Browser: Brave Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (x86_64)
 - Slidev version: 0.38.3
